apiVersion: v1
kind: Service
metadata:
  name: micro-flask-svc
  namespace: ibcdev
  labels:
    service: flask
spec:
  selector:
    app: microflask
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
